FROM alpine:latest
RUN apk add --no-cache openjdk21
WORKDIR /app
COPY ./music/target/musician-1.0-jar-with-dependencies.jar /app/

# Run the JAR file when the container launches
ENTRYPOINT ["java", "-jar", "musician-1.0-jar-with-dependencies.jar"]
